import { Box, styled, keyframes, Card, CardContent, Typography, Grid } from '@mui/material'
import StarIcon from '@mui/icons-material/Star';
import Head from 'next/head'
import Image from 'next/image'
import Mech from '../public/gruntz_mech.jpg'
import Cover from '../public/cover2.jpg'


export default function Home() {
  const bgImageUrl = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1440 900'%3E%3Cdefs%3E%3ClinearGradient id='grad1' x1='0%25' y1='0%25' x2='100%25' y2='0%25'%3E%3Cstop offset='0%25' stop-color='%230a0c1f'/%3E%3Cstop offset='100%25' stop-color='%23262b4e'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23grad1)' /%3E%3Ccircle cx='100' cy='100' r='3' fill='%23fff' /%3E%3Ccircle cx='200' cy='250' r='2' fill='%23fff' /%3E%3Ccircle cx='300' cy='400' r='2' fill='%23fff' /%3E%3C/svg%3E";

  return (
    <div
      style={{
        backgroundImage: `url(${bgImageUrl})`,
        transition: "background-position 1s linear",
        backgroundPosition: "0 0",
        animationName: "background-animation",
        animationDuration: "60s",
        animationTimingFunction: "linear",
        animationIterationCount: "infinite",
      }}
    >
      <Head>
        <title>Iron Hearts Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          container
        >
          <Grid item xs={6}>
            <div style={{ position: 'relative', width: '100%', height: 0, paddingBottom: '100%' }}>
              <Image 
                src={Cover}
                alt="IH-Cover"
                fill
                object-fit="cover"
                objectPosition="center"
              />
            </div>
          </Grid>
          <Grid item xs={6} container justifyContent="center" alignItems="center">
            <Card sx={{ maxWidth: 345, width: 500, height: 500 }}>
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  My Title
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Some description text goes here.
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={6}>
            <h1> Card </h1>
          </Grid>
          <Grid item xs={6}>
            <div style={{ position: 'relative', width: '100%', height: 0, paddingBottom: '100%' }}>
                <Image 
                  src={Mech}
                  alt="IH-Mech"
                  fill
                  object-fit="cover"
                  objectPosition="center"
                />
            </div>
          </Grid>
        </Grid>
      </main>
    </div>
  )
}
