/* eslint-disable react/no-unescaped-entities */
import { useMediaQuery, Typography, Grid } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Mech from '../public/gruntz_mech.jpg'
import Cover from '../public/Cover2.png'
import { FormattedMessage } from 'react-intl'


export default function Home() {
  const isLargeScreen = useMediaQuery((theme) => theme.breakpoints.down("xl"));
  const headerSize = isLargeScreen ? "h7" : "h6"
  return (
    <>
      <Head>
        <title>Iron Hearts Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container>
          <Grid item xs={12} md={6}>
            <div style={{ position: 'relative', width: '100%', height: 0, paddingBottom: '100%' }}>
              <Image 
                src={Cover}
                alt="IH-Cover"
                fill
                object-fit="cover"
                objectPosition="center"
              />
            </div>
          </Grid>
          <Grid item  xs={12} md={6} container justifyContent="center" alignItems="center" sx={{ zIndex: 1, p: 5 }}>
            <Typography variant={headerSize} align="center">
                <p><FormattedMessage id="landingPitch1"/></p><br/>
                <p><FormattedMessage id="landingPitch2"/></p><br/>
                <p><FormattedMessage id="landingPitch3Alt"/></p><br/>
                {/* <p><FormattedMessage id="landingPitch3"/></p><br/> */}
            </Typography>
          </Grid> 
          <Grid item xs={12} md={6} container justifyContent="center" alignItems="center" sx={{ zIndex: 1, p: 5 }}>
            <Typography variant={headerSize} align="center">
              <ul>
              <FormattedMessage id="mavQuote"/> <br/><span> - General Mavernic LMCF </span>
              </ul>
              <br/><br/>
              <ul>
                <FormattedMessage id="holtonQuote"/> <br/><span> - General Holton EFSF </span>
              </ul>
              <br/><br/>
              <ul>
                <FormattedMessage id="johnQuote"/>               
                <br/><span> - John </span>
              </ul>
            </Typography>
          </Grid>
          <Grid item xs={12} md={6}>
            <div style={{ position: 'relative', width: '100%', height: 0, paddingBottom: '100%' }}>
                <Image 
                  src={Mech}
                  alt="IH-Mech"
                  fill
                  object-fit="cover"
                  objectPosition="center"
                />
            </div>
          </Grid>
        </Grid>
      </main>
    </>
  )
}
